package ch.inf.usi.mindbricks.model.questionnare;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import ch.inf.usi.mindbricks.model.visual.StudySession;
import ch.inf.usi.mindbricks.util.questionnaire.ProductivityQuestionnaireResult;

/**
 * Entity representing a post-session questionnaire filled by the user (emotion and perceived productivity)
 *
 * @author Marta Šafářová
 * <p>
 * Refactored by:
 * @author Luca Di Bello
 */
@Entity(tableName = "session_questionnaires",
        foreignKeys = @ForeignKey(
                entity = StudySession.class,
                parentColumns = "id",
                childColumns = "sessionId",
                // Delete questionnaire if session is deleted
                onDelete = ForeignKey.CASCADE
        ),
        indices = {@Index(value = "sessionId")})
public class SessionQuestionnaire {

    /**
     * Primary key for the questionnaire, auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    private long id;

    /**
     * Foreign key reference to the associated study session.
     */
    private long sessionId;

    /**
     * Timestamp when the questionnaire was created.
     * Automatically generated by the database using SQLite's current timestamp.
     */
    @ColumnInfo(defaultValue = "(strftime('%s', 'now') * 1000)")
    private long timeStamp;

    /**
     * Emotion rating based on the PAM (Photographic Affect Meter) scale.
     * Range: 0-6 scale representing different emotional states.
     */
    private int emotionRating;

    /**
     * Flag indicating whether the user completed the perceived productivity questionnaire.
     */
    private boolean hasProductivityQuestions;

    /**
     * Rating for enthusiasm level during the study session.
     * Null if detailed questions were not answered.
     */
    private Integer enthusiasmRating;

    /**
     * Rating for energy level during the study session.
     * Null if detailed questions were not answered.
     */
    private Integer energyRating;

    /**
     * Rating for engagement level during the study session.
     * Null if detailed questions were not answered.
     */
    private Integer engagementRating;

    /**
     * Rating for satisfaction level with the study session.
     * Null if detailed questions were not answered.
     */
    private Integer satisfactionRating;

    /**
     * Rating for anticipation/motivation level for future sessions.
     * Null if detailed questions were not answered.
     */
    private Integer anticipationRating;

    /**
     * Default constructor required by Room.
     */
    public SessionQuestionnaire() {
    }

    /**
     * Constructor for creating a quick questionnaire with only emotion data.
     *
     * @param sessionId     the ID of the associated study session
     * @param emotionRating the emotion rating (0-6 PAM scale)
     */
    @Ignore
    public SessionQuestionnaire(long sessionId, int emotionRating) {
        this.sessionId = sessionId;
        this.emotionRating = emotionRating;
        this.hasProductivityQuestions = false;
    }

    /**
     * Constructor for creating a detailed questionnaire with all productivity metrics.
     *
     * @param sessionId          the ID of the associated study session
     * @param emotionRating      the emotion rating (0-6 PAM scale)
     * @param enthusiasmRating   rating for enthusiasm level
     * @param energyRating       rating for energy level
     * @param engagementRating   rating for engagement level
     * @param satisfactionRating rating for satisfaction level
     * @param anticipationRating rating for anticipation/motivation level
     */
    @Ignore
    public SessionQuestionnaire(long sessionId, int emotionRating,
                                int enthusiasmRating, int energyRating, int engagementRating,
                                int satisfactionRating, int anticipationRating) {
        this.sessionId = sessionId;
        this.emotionRating = emotionRating;
        this.enthusiasmRating = enthusiasmRating;
        this.energyRating = energyRating;
        this.engagementRating = engagementRating;
        this.satisfactionRating = satisfactionRating;
        this.anticipationRating = anticipationRating;
        this.hasProductivityQuestions = true;
    }

    /**
     * Factory method to create a SessionQuestionnaire from a ProductivityQuestionnaireResult.
     *
     * @param sessionId     the ID of the associated study session
     * @param emotionRating the emotion rating (0-6 PAM scale)
     * @param result        the detailed questionnaire result (null if quick questionnaire)
     * @return the created SessionQuestionnaire
     */
    public static SessionQuestionnaire from(long sessionId,
                                            int emotionRating,
                                            @Nullable ProductivityQuestionnaireResult result) {
        // if no result -> quick questionnaire
        if (result == null) {
            return new SessionQuestionnaire(sessionId, emotionRating);
        }
        // otherwise -> detailed questionnaire
        return new SessionQuestionnaire(
                sessionId,
                emotionRating,
                result.enthusiasm(),
                result.energy(),
                result.engagement(),
                result.satisfaction(),
                result.anticipation()
        );
    }


    /**
     * Gets the questionnaire ID.
     *
     * @return the auto-generated questionnaire ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the questionnaire ID.
     *
     * @param id the questionnaire ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the associated study session ID.
     *
     * @return the study session ID
     */
    public long getSessionId() {
        return sessionId;
    }

    /**
     * Sets the associated study session ID.
     *
     * @param sessionId the study session ID
     */
    public void setSessionId(long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Gets the timestamp when the questionnaire was created.
     *
     * @return timestamp in milliseconds since Unix epoch
     */
    public long getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the timestamp for the questionnaire.
     * Note: This is typically auto-generated by the database.
     *
     * @param timestamp timestamp in milliseconds since Unix epoch
     */
    public void setTimeStamp(long timestamp) {
        this.timeStamp = timestamp;
    }

    /**
     * Gets the emotion rating.
     *
     * @return emotion rating on 0-6 PAM scale
     */
    public int getEmotionRating() {
        return emotionRating;
    }

    /**
     * Sets the initial emotion rating.
     *
     * @param emotionRating emotion rating on 0-6 PAM scale
     */
    public void setEmotionRating(int emotionRating) {
        this.emotionRating = emotionRating;
    }

    /**
     * Checks if detailed productivity questions were answered.
     *
     * @return true if detailed questions were answered, false otherwise
     */
    public boolean isHasProductivityQuestions() {
        return hasProductivityQuestions;
    }

    /**
     * Sets whether detailed productivity questions were answered.
     *
     * @param hasProductivityQuestions true if detailed questions were answered
     */
    public void setHasProductivityQuestions(boolean hasProductivityQuestions) {
        this.hasProductivityQuestions = hasProductivityQuestions;
    }

    /**
     * Gets the enthusiasm rating.
     *
     * @return enthusiasm rating, or null if detailed questions were not answered
     */
    public Integer getEnthusiasmRating() {
        return enthusiasmRating;
    }

    /**
     * Sets the enthusiasm rating.
     *
     * @param enthusiasmRating enthusiasm rating value
     */
    public void setEnthusiasmRating(Integer enthusiasmRating) {
        this.enthusiasmRating = enthusiasmRating;
    }

    /**
     * Gets the energy rating.
     *
     * @return energy rating, or null if detailed questions were not answered
     */
    public Integer getEnergyRating() {
        return energyRating;
    }

    /**
     * Sets the energy rating.
     *
     * @param energyRating energy rating value
     */
    public void setEnergyRating(Integer energyRating) {
        this.energyRating = energyRating;
    }

    /**
     * Gets the engagement rating.
     *
     * @return engagement rating, or null if detailed questions were not answered
     */
    public Integer getEngagementRating() {
        return engagementRating;
    }

    /**
     * Sets the engagement rating.
     *
     * @param engagementRating engagement rating value
     */
    public void setEngagementRating(Integer engagementRating) {
        this.engagementRating = engagementRating;
    }

    /**
     * Gets the satisfaction rating.
     *
     * @return satisfaction rating, or null if detailed questions were not answered
     */
    public Integer getSatisfactionRating() {
        return satisfactionRating;
    }

    /**
     * Sets the satisfaction rating.
     *
     * @param satisfactionRating satisfaction rating value
     */
    public void setSatisfactionRating(Integer satisfactionRating) {
        this.satisfactionRating = satisfactionRating;
    }

    /**
     * Gets the anticipation/motivation rating.
     *
     * @return anticipation rating, or null if detailed questions were not answered
     */
    public Integer getAnticipationRating() {
        return anticipationRating;
    }

    /**
     * Sets the anticipation/motivation rating.
     *
     * @param anticipationRating anticipation rating value
     */
    public void setAnticipationRating(Integer anticipationRating) {
        this.anticipationRating = anticipationRating;
    }

    /**
     * Checks if all detailed productivity ratings are present and valid.
     * Useful for analytics and graph generation.
     *
     * @return true if all detailed ratings are non-null, false otherwise
     */
    public boolean hasCompleteRatings() {
        return hasProductivityQuestions &&
                enthusiasmRating != null &&
                energyRating != null &&
                engagementRating != null &&
                satisfactionRating != null &&
                anticipationRating != null;
    }

    /**
     * Calculates the average rating across all detailed productivity metrics.
     * Prepared for future use in graphs and analytics.
     *
     * @return average rating (0.0-max scale), or -1 if ratings are incomplete
     */
    public float getAverageRating() {
        if (!hasCompleteRatings()) {
            return -1f;
        }
        return (enthusiasmRating + energyRating + engagementRating +
                satisfactionRating + anticipationRating) / 5f;
    }

    /**
     * Returns a string representation of the questionnaire for debugging.
     *
     * @return string containing all questionnaire fields
     */
    @NonNull
    @Override
    public String toString() {
        return "SessionQuestionnaire{" +
                "id=" + id +
                ", sessionId=" + sessionId +
                ", timestamp=" + timeStamp +
                ", initialEmotion=" + emotionRating +
                ", answeredDetailedQuestions=" + hasProductivityQuestions +
                ", enthusiasmRating=" + enthusiasmRating +
                ", energyRating=" + energyRating +
                ", engagementRating=" + engagementRating +
                ", satisfactionRating=" + satisfactionRating +
                ", anticipationRating=" + anticipationRating +
                '}';
    }
}
